### PR TITLE
Legacy resource registries made optional

### PR DESCRIPTION
**Pull request by ksuess**
Products.ResourceRegistries (portal_css, portal_javascript) is replaced by new type Resource Registries https://docs.plone.org/adapt-and-extend/config/resource-registries.html

### CODE REVIEW

**Comment by ksuess** [comment]
Should the legacy resource registries portal_css, portal_javascript, portal_kss be regarded anymore if they are installed ? If not, what is necessary to mark the next version of plone.app.caching as not supporting the legacy resource registiries?

**Comment by ksuess** [comment]
`Error: The requirement ('transaction>=2.4') is not allowed by your [versions] constraint (2.2.1)`

Any hint, why this fails?

**Comment by pbauer** [comment]
Zope master upgraded its dependencies. Buildout is now running again but there are still test-failure caused by the new `__repr__` persistent that I am trying to fix with https://github.com/zopefoundation/Zope/pull/392.

**Comment by jensens** [comment]
LGTM, but before merge we must branch away for 5.1.x and earlier and use master for 5.2 only.

**Comment by ksuess** [comment]
> LGTM, but before merge we must branch away for 5.1.x and earlier and use master for 5.2 only.

Master is now for Plone 5.2. which is the first version without legacy resource registries.
Branch 1.x respects Plone 5.1 and earlier. This is noted in coredev buildout.

@jensens Please have look and merge. Thank you.

**Pull request merged**
