### PR TITLE
Add more purge paths for images and downloads

### PR DESCRIPTION
**Pull request by jensens**
Additional valid purge paths for image and file fields.

### CODE REVIEW

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Review by tisto — APPROVED** [review]
LGTM.

**Comment by tisto** [comment]
@jensens seems lots of p.a.caching tests fail on Jenkins...

**Comment by jensens** [comment]
As usual tests need more love.

**Comment by jensens** [comment]
@tisto, tests on master and here are back to green (local run, coredev 6). I think its ready for merge.

**Pull request merged**
