### PR TITLE
No request

### LINKED ISSUE #56: Fails to purge if there is no request
On our policy package we enable cache purging and afterwards on the setuphandlers of our profile we create a few objects already.

With the purging already enabled this means that the objects would be purged, but at that time there is no request, as it is setting up the package.

Since [this change](https://github.com/plone/plone.app.caching/commit/c10e1997b4f35b11abbd9836631deb2fc0e1acc7), or, starting with plone.app.caching 2.0.1 this current setup explain above is broken.

A possible fix would be to first check if there is a request at all. I will provide a pull request right away. I needed an issue number to create the news snippet :smile:

### PR DESCRIPTION
**Pull request by gforcada**
Fixes #56

### CODE REVIEW

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
@gforcada, you are working on this pr. Shall we wait with a release? I am interested in a release for merged https://github.com/plone/plone.app.caching/pull/55.

**Comment by gforcada** [comment]
No need to wait for this to get merged to get a new release out, if the fix I'm trying to fix here has been on a release for quite a few releases already it will not hurt to get into yet another one.

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
This is failing for real `plone.app.caching.tests.test_purge.TestPurgeRedispatch.test_removed`
```
Failing for the past 1 build (Since Failed#1237 )
Took 0 ms.
Error Message
2 != 0
Stacktrace
2 != 0

  File "/srv/python3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/srv/python3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/jenkins/workspace/pull-request-5.2-3.6/src/plone.app.caching/plone/app/caching/tests/test_purge.py", line 182, in test_removed
    self.assertEqual(2, len(self.handler.invocations))
  File "/srv/python3.6/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/srv/python3.6/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
```

**Comment by gforcada** [comment]
Now there is an exact copy of this one on #59 :shrug:

**Pull request closed without merging**
