### PR TITLE
Remove unused redirectOnResponse from pat-modal links

### PR DESCRIPTION
**Pull request by fulv**
See Products.CMFPlone#3197

### CODE REVIEW

**Comment by fulv** [comment]
(typo)
See Products.CMFPlone#3197

**Comment by fulv** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs.

**Review by tisto — APPROVED** [review]
LGTM.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs.

**Pull request merged**
