### PR TITLE
remove gzip option

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
jenkins test: http://jenkins.plone.org/job/pull-request-5.0/7/

**Comment by vangheem** [comment]
one more time: http://jenkins.plone.org/job/pull-request-5.0/8/

**Comment by vangheem** [comment]
besides for @tkimnguyen no one is yelling at me about this :). The issue was up fro 2 years with no formal objections. I'm going to merge.

**Comment by jensens** [comment]
because of semantic versioning this is in my opinion a 1.3 version, just my 0.02 €

**Comment by vangheem** [comment]
1.2 is already plone 5 only so I think we're okay.

**Comment by tisto** [comment]
I agree with @jensens. Any API change requires at least a minor release step according to semantic versioning: http://semver.org/

Going from 1.2.6 to 1.2.7 would be ok for bugfixes only.

**Comment by jensens** [comment]
yeah, http://semver.org/ basics is something we should print on next plone conference t-shirts.

**Pull request merged**
