### PR TITLE
Do not assume request URL is a string. It might be None.

### PR DESCRIPTION
**Pull request by jensens**
This may happen on layer setup in tests if request was not initialized already properly.

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
Addresses also #56

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
Yes, addresses #56 and for that I did #57 but seems nobody cared about it :shrug:

**Review by ale-rt — APPROVED** [review]
LGTM

**Comment by jensens** [comment]
@gforcada maybe because tests were red as mine are...

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
