### PR TITLE
Fix css classes for `<select />` in controlpanel

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
What are you trying to solve here? Should I see a difference?
I see this on master:

Screenshot 2023-01-25 at 17 38 21

I see no difference visually on your branch. This is with Firefox on Mac.

**Comment by petschki** [comment]
Ah ... for multiselects there's no (obvious) difference. The single selects in "Cache operations" are missing the caret down:

before:
Bildschirmfoto 2023-01-25 um 18 05 27

after:
Bildschirmfoto 2023-01-25 um 18 05 20

for consistency I've added the `form-select` classes to the `<select>` tags.

**Review by mauritsvanrees — APPROVED** [review]
Ah, now I see. That is better indeed. Checked and confirmed locally.
Thanks!

**Pull request merged**
