### PR TITLE
Fix controlpanel for Python 3

### LINKED ISSUE #48: Control panel cannot be saved in Python 3
see https://github.com/plone/Products.CMFPlone/issues/2796 for details

### PR DESCRIPTION
**Pull request by petschki**
fixes #48

### CODE REVIEW

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
@petschki would you mind adding a changelog entry?

**Comment by tisto** [comment]
@petschki did you forgot to push something? I only see changes in the test setup, not in the actual code.

**Comment by petschki** [comment]
@tisto this is still in progress ... I'll push all changes later today ... had to investigate related problems to this (see https://github.com/zopefoundation/plone.z3cform/pull/25)

**Comment by petschki** [comment]
When tests go green, this can be merged.  Jenkins Parameter:
```
https://github.com/zopefoundation/plone.z3cform/pull/25
https://github.com/plone/plone.app.caching/pull/49
```

**Comment by tisto** [comment]
If I am not mistaken, it is possible to run the pull request jobs on Jenkins against multiple branches. I gave it a try: 

https://jenkins.plone.org/job/pull-request-5.1/2/console

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Comment by tisto** [comment]
Seems that Jenkins can not pull from the zopefoundation org on github. Error trace:

Could not update Pull Request https://github.com/zopefoundation/plone.z3cform/pull/25

https://jenkins.plone.org/job/pull-request-5.1/3/console

**Comment by petschki** [comment]
@tisto yes... this is what I already did, but I think jenkins somehow doesn't want to mark this as green though all tests pass ... and in Python 3 no tests are startet ... see https://jenkins.plone.org/job/pull-request-5.2/8/ ... I already asked @gforcada on community.plone.org if there are problems due to the server change...

And these PRs are for Plone 5.2 only btw...

**Comment by petschki** [comment]
@tisto and you have to run the jenkins job manually with both PR urls ... the comment only starts this URL ...

**Comment by petschki** [comment]
@tisto I think the jenkins failures are all due to unauthorized zopefoundation repo ... in order to get these tests running we should merge and release https://github.com/zopefoundation/plone.z3cform/pull/25 ... can you do that?

**Comment by petschki** [comment]
finally ... this is ready ... but py3 needs `plone.z3cform>=1.1.0` released too

**Pull request merged**
